### ISSUE TITLE
bundle exec jekyll serve 

### ISSUE THREAD

**Issue by Xiangyue-Zhang** [alshedivat/al-folio#1116]
I've already installed it from the video and installed the environment using bundle install. But it was during bundle exec jekyll serve that the following error occurred. How should I solve it? And I've already commented that out
"#external_sources:
#- name: medium.com
#rss_url: https://medium.com/@al-folio/feed"
```
Configuration file: C:/Users/zxylocal/Desktop/Xiangyue-Zhang.github.io/xiangyue-zhang.github.io/_config.yml
            Source: C:/Users/zxylocal/Desktop/Xiangyue-Zhang.github.io/xiangyue-zhang.github.io
       Destination: C:/Users/zxylocal/Desktop/Xiangyue-Zhang.github.io/xiangyue-zhang.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
       Imagemagick: Disabled in site.config
       Jekyll Feed: Generating feed for posts
  Liquid Exception: SSL_connect returned=1 errno=0 peeraddr=202.160.128.210:443 state=error: unexpected eof while reading in C:/Users/zxylocal/Desktop/Xiangyue-Zhang.github.io/xiangyue-zhang.github.io/_posts/2020-09-28-twitter.md
                    ------------------------------------------------
      Jekyll 4.3.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/3.2.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=202.160.128.210:443 state=error: unexpected eof while reading (OpenSSL::SSL::SSLError)
        from D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/3.2.0/net/protocol.rb:46:in `ssl_socket_connect'
        from D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/3.2.0/net/http.rb:1342:in `connect'
        from D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
        from D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/3.2.0/net/http.rb:1237:in `start'
        from D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/3.2.0/net/http.rb:687:in `start'
        from D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-twitter-plugin-2.1.0/lib/jekyll-twitter-plugin.rb:73:in `fetch'
        from D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-twitter-plugin-2.1.0/lib/jekyll-twitter-plugin.rb:209:in `live_response'
        from D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-twitter-plugin-2.1.0/lib/jekyll-twitter-plugin.rb:180:in `render'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:129:in `render_liquid'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:80:in `render_document'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:63:in `run'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:578:in `render_regenerated'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:563:in `block (2 levels) in render_docs'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:562:in `each'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:562:in `block in render_docs'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:561:in `each_value'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:561:in `render_docs'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:210:in `render'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/site.rb:80:in `process'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:28:in `process_site'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Users/zxylocal/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.1/exe/jekyll:15:in `<top (required)>'
        from C:/Users/zxylocal/AppData/Local/Microsoft/WindowsApps/jekyll:32:in `load'
        from C:/Users/zxylocal/AppData/Local/Microsoft/WindowsApps/jekyll:32:in `<main>'
```

**Comment by alshedivat** [comment]
can you try removing `_posts/2020-09-28-twitter.md` example post?

**Comment by Xiangyue-Zhang** [comment]
> can you try removing `_posts/2020-09-28-twitter.md` example post?

I‘ve tried.And here comes a new problem.

```
Configuration file: C:/Users/zxylocal/Desktop/io/xiangyue-zhang.github.io/_config.yml
            Source: C:/Users/zxylocal/Desktop/io/xiangyue-zhang.github.io
       Destination: C:/Users/zxylocal/Desktop/io/xiangyue-zhang.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
       Imagemagick: Disabled in site.config
       Jekyll Feed: Generating feed for posts
   Jekyll Diagrams: Command Not Found: mmdc
  Liquid Exception: undefined method `exists?' for File:Class in C:/Users/zxylocal/Desktop/io/xiangyue-zhang.github.io/_layouts/about.html
                    ------------------------------------------------
      Jekyll 4.3.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
D:/0SoftwareDownload/Ruby/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-scholar-7.1.1/lib/jekyll/scholar/utilities.rb:471:in `scholar_source': undefined method `exists?' for File:Class (NoMethodError)

        return source if source.start_with?('/') && File.exists?(source)
                                                        ^^^^^^^^
Did you mean?  exist?
```

**Comment by kvishalrai** [comment]
Getting same problem as @Xiangyue-Zhang

**Comment by sekarshre** [comment]
Hello, (new user here)

I was just about to post the same problem as above. I unable to get jekyll-scholar to compile the bibliography as I'm getting the same error.

```
 Liquid Exception: undefined method `exists?' for File:Class in C:/Users/shrey/Documents/Website/al-folio-master/_layouts/about.html
                    ------------------------------------------------
      Jekyll 4.3.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-scholar-7.1.1/lib/jekyll/scholar/utilities.rb:471:in `scholar_source': undefined method `exists?' for File:Class (NoMethodError)

        return source if source.start_with?('/') && File.exists?(source)
                                                        ^^^^^^^^
Did you mean?  exist?
```

Here's a few things I tried:

1. I went into scholar/utilities.rb and tried changing exists?(name) ---> exist?(name). After this, I was able to run bundle exec jekyll serve. Unfortunately, my bibliography did not compile and as a result, I wasn't able to get my publication page to load.

2. To check if the problem was with jekyll-scholar, I tried running a different jekyll theme. But my bibliography seemed to compile okay there. 

I'm stuck now and I would really appreciate some help on dealing with this issue. Thanks a lot!

**Comment by kvishalrai** [comment]
Perfect! Works now, thanks. :)
