### ISSUE TITLE
cannot launch website locally using docker-compose up

### ISSUE THREAD

**Issue by tanmayyb** [alshedivat/al-folio#1156]
Help!
I am trying to launch the template on windows after having setup docker desktop (+ compose). I entered the command 
```
docker-compose up
```
But the process exits with code 1. The container doesn't stay running and I can't view the template on localhost.
The full log is very long so here is small description. I get a bunch of _stack level too deep text_ in red like this:
```
al-folio-website  |   Liquid Exception: stack level too deep in /srv/jekyll/_posts/2021-07-04-diagrams.md/#excerpt
al-folio-website  |   Liquid Exception: stack level too deep in /srv/jekyll/_posts/2021-07-04-diagrams.md/#excerpt
al-folio-website  |   Liquid Exception: stack level too deep in /srv/jekyll/_posts/2021-07-04-diagrams.md/#excerpt
```
and then this text which seems like an error:
```
al-folio-website  | bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
al-folio-website  | /var/lib/gems/2.7.0/gems/colorator-1.1.0/lib/colorator/core_ext.rb:4:in `public_send': stack level too deep (SystemStackError)
al-folio-website  |     from /var/lib/gems/2.7.0/gems/colorator-1.1.0/lib/colorator/core_ext.rb:4:in `block (2 levels) in <class:String>'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/jekyll-4.3.1/lib/jekyll/stevenson.rb:43:in `error'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/jekyll-4.3.1/lib/jekyll/log_adapter.rb:148:in `public_send'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/jekyll-4.3.1/lib/jekyll/log_adapter.rb:148:in `write'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/jekyll-4.3.1/lib/jekyll/log_adapter.rb:86:in `error'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:132:in `rescue in render_liquid'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:123:in `render_liquid'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/jekyll-4.3.1/lib/jekyll/renderer.rb:80:in `render_document'
al-folio-website  |      ... 10144 levels...
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.3/exe/bundler:4:in `load'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.3/exe/bundler:4:in `<top (required)>'
al-folio-website  |     from /usr/local/bin/bundler:23:in `load'
al-folio-website  |     from /usr/local/bin/bundler:23:in `<main>'
al-folio-website exited with code 1
```

Please help, thanks!

**Comment by tanmayyb** [comment]
OK after doing some more research I found that this is very similar to the issue #965. I followed the remedy in that issue and now I am able to run the template.
