### ISSUE TITLE
Could not find gem 'wdm (>= 0.1.0)' in locally installed gems. (Bundler::GemNotFound) - Al-folio Docker Image

### ISSUE THREAD

**Issue by HomayoonT** [alshedivat/al-folio#1180]
**Describe the bug**
```
[+] Running 2/2
 - Network jekyll-al-folio-blog_default  Created                                                                   1.0s
 - Container al-folio-website            Created                                                                   2.6s
Attaching to al-folio-website
al-folio-website  | bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
al-folio-website  | /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/resolver.rb:293:in `raise_not_found!': Could not find gem 'wdm (>= 0.1.0)' in locally installed gems. (Bundler::GemNotFound)
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/resolver.rb:346:in `block in prepare_dependencies'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/resolver.rb:331:in `each'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/resolver.rb:331:in `map'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/resolver.rb:331:in `prepare_dependencies'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/resolver.rb:51:in `setup_solver'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/resolver.rb:28:in `start'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/definition.rb:554:in `start_resolution'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/definition.rb:289:in `resolve'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/definition.rb:507:in `materialize'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/definition.rb:197:in `specs'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/definition.rb:254:in `specs_for'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/runtime.rb:18:in `setup'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler.rb:170:in `setup'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/setup.rb:20:in `block in <top (required)>'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/ui/shell.rb:159:in `with_level'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/ui/shell.rb:111:in `silence'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/setup.rb:20:in `<top (required)>'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:56:in `require_relative'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:56:in `kernel_load'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/exe/bundler:4:in `load'
al-folio-website  |     from /var/lib/gems/2.7.0/gems/bundler-2.4.6/exe/bundler:4:in `<top (required)>'
al-folio-website  |     from /usr/local/bin/bundler:23:in `load'
al-folio-website  |     from /usr/local/bin/bundler:23:in `<main>'
al-folio-website exited with code 1
```
**To Reproduce**
1. Cloned the repository
2. `docker-compose up`
3. Saw the error

**Expected behavior**
I expected the instructions given on the [main page](https://github.com/alshedivat/al-folio) to work.

**System (please complete the following information):**
 - Host OS in which docker is running on is Win 10

**Additional context**
It seems that instructions in the `Dockerfile` installs `Ruby 2.7.0`.
Referring to the following instruction:
`RUN apt-get install --no-install-recommends ruby-full build-essential zlib1g-dev -y `

In addition, the following is the content of my `Gemfile`
```
source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-imagemagick'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-link-attributes'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    # gem 'mini_racer'
    gem 'unicode_utils'
    gem 'webrick'
end
group :other_plugins do
    gem 'httparty'
    gem 'feedjira'
    gem 'wdm', '>=0.1.0'
end
```

**Comment by alicelovestocode** [comment]
If you are using docker then you don't need `gem 'wdm (>= 0.1.0)'` in your gemfile.

I had this error when I moved from running `bundle exec jekyll serve` to `docker-compose up`.

Deleting the line from the gemfile solved the error.
