### ISSUE TITLE
"bundler exec jekyll serve" creates error

### ISSUE THREAD

**Issue by tasanyphy01773** [alshedivat/al-folio#1186]
### Discussed in https://github.com/alshedivat/al-folio/discussions/1176

<div type='discussions-op-text'>

<sup>Originally posted by **tasanyphy01773** February 11, 2023</sup>
Hi. Thanks in advance for your help.
So I was trying to make my own portfolio with this repo. This is the error I get when commanding 'bundler exec jekyll serve'. System details are below. For more context, I get an error earlier that the system couldn't find mini racer, then I tried linking like  [this](https://github.com/rubyjs/mini_racer/issues/250#user-content-fnref-1-3168b0b280f52a25878525e591d3b862) and it was solved, but now here I stuck.

```
(base) sany@asus:~/Desktop/temp_website/Fahad_bhai/Main_file$ bundle install
Using concurrent-ruby 1.2.0
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.7.0
  /var/lib/gems/2.7.0/build_info
  /var/lib/gems/2.7.0/cache
  /var/lib/gems/2.7.0/doc
  /var/lib/gems/2.7.0/extensions
  /var/lib/gems/2.7.0/gems
  /var/lib/gems/2.7.0/specifications
Using i18n 1.12.0
Using minitest 5.17.0
Using tzinfo 2.0.6
Using activesupport 7.0.4.2
Using public_suffix 5.0.1
Using addressable 2.8.1
Using latex-decode 0.4.0
Using bibtex-ruby 6.0.0
Using bundler 2.1.4
Using namae 1.1.1
Using citeproc 1.0.10
Using rexml 3.2.5
Using csl 1.6.0
Using citeproc-ruby 1.1.14
Using colorator 1.1.0
Using crass 1.0.6
Using csl-styles 1.0.1.11
Using cssminify2 2.0.1
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using em-websocket 0.5.3
Using execjs 2.8.1
Using mini_portile2 2.8.1
Using racc 1.6.2
Using nokogiri 1.14.1 (x86_64-linux)
Using loofah 2.19.1
Using sax-machine 1.3.2
Using feedjira 3.2.2
Using ffi 1.15.5
Using forwardable-extended 2.6.0
Using gemoji 4.0.1
Using html-pipeline 2.14.3
Using htmlcompressor 0.4.0
Using mini_mime 1.1.2
Using multi_xml 0.6.0
Using httparty 0.21.0
Using sassc 2.4.0
Using jekyll-sass-converter 2.2.0
Using rb-fsevent 0.11.2
Using rb-inotify 0.10.1
Using listen 3.8.0
Using jekyll-watch 2.2.1
Using kramdown 2.4.0
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.4
Using mercenary 0.4.0
Using pathutil 0.16.2
Using rouge 4.0.1
Using safe_yaml 1.0.5
Using unicode-display_width 2.4.2
Using terminal-table 3.0.2
Using webrick 1.8.1
Using jekyll 4.3.2
Using jekyll-archives 2.2.1
Using jekyll-diagrams 0.10.0
Using jekyll-email-protect 1.1.0
Using jekyll-feed 0.17.0
Using jekyll-imagemagick 1.4.0
Using jekyll-link-attributes 1.0.1
Using json 2.6.3
Using json-minify 0.0.3
Using uglifier 4.2.0
Using jekyll-minifier 0.1.10
Using jekyll-paginate-v2 3.0.0
Using jekyll-scholar 7.1.2
Using jekyll-sitemap 1.4.0
Using jekyll-twitter-plugin 2.1.0
Using jemoji 0.13.0
Using libv8-node 16.10.0.0 (x86_64-linux-musl)
Using mini_racer 0.6.3
Using unicode_utils 1.4.0
Bundle complete! 18 Gemfile dependencies, 72 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
(base) sany@asus:~/Desktop/temp_website/Fahad_bhai/Main_file$ bundle exec jekyll build
Traceback (most recent call last):
	12: from /usr/local/bin/jekyll:23:in `<main>'
	11: from /usr/local/bin/jekyll:23:in `load'
	10: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/exe/jekyll:8:in `<top (required)>'
	 9: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/exe/jekyll:8:in `require'
	 8: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:191:in `<top (required)>'
	 7: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:12:in `require_all'
	 6: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:12:in `each'
	 5: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:13:in `block in require_all'
	 4: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:13:in `require'
	 3: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:3:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:4:in `<module:Jekyll>'
	 1: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:5:in `<module:Drops>'
/var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:10:in `<class:CollectionDrop>': undefined method `delegate_method_as' for Jekyll::Drops::CollectionDrop:Class (NoMethodError)
Did you mean?  DelegateClass
(base) sany@asus:~/Desktop/temp_website/Fahad_bhai/Main_file$ bundle exec jekyll serve
Traceback (most recent call last):
	12: from /usr/local/bin/jekyll:23:in `<main>'
	11: from /usr/local/bin/jekyll:23:in `load'
	10: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/exe/jekyll:8:in `<top (required)>'
	 9: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/exe/jekyll:8:in `require'
	 8: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:191:in `<top (required)>'
	 7: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:12:in `require_all'
	 6: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:12:in `each'
	 5: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:13:in `block in require_all'
	 4: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:13:in `require'
	 3: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:3:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:4:in `<module:Jekyll>'
	 1: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:5:in `<module:Drops>'
/var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:10:in `<class:CollectionDrop>': undefined method `delegate_method_as' for Jekyll::Drops::CollectionDrop:Class (NoMethodError)
Did you mean?  DelegateClass
```

System :

OS: Linux asus 5.8.0-63-generic #71~20.04.1-Ubuntu
Browser: Chrome
Jekyll version: I get error See below
Ruby version see below
```
(base) sany@asus:~$ jekyll -v
Traceback (most recent call last):
	14: from /usr/local/bin/jekyll:23:in `<main>'
	13: from /usr/local/bin/jekyll:23:in `load'
	12: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/exe/jekyll:8:in `<top (required)>'
	11: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	10: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 9: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:191:in `<top (required)>'
	 8: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:12:in `require_all'
	 7: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:12:in `each'
	 6: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll.rb:13:in `block in require_all'
	 5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:3:in `<top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:4:in `<module:Jekyll>'
	 1: from /var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:5:in `<module:Drops>'
/var/lib/gems/2.7.0/gems/jekyll-4.3.2/lib/jekyll/drops/collection_drop.rb:10:in `<class:CollectionDrop>': undefined method `delegate_method_as' for Jekyll::Drops::CollectionDrop:Class (NoMethodError)
(base) sany@asus:~$ gem -v
3.1.2
(base) sany@asus:~$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

```
</div>

**Comment by tasanyphy01773** [comment]
I have installed ruby twice and before installing `gem install jekyll bundler` I need to restart your terminal, that solved the problem
