### ISSUE TITLE
Getting errors while deployment (bin/deploy --user)

### ISSUE THREAD

**Issue by anmspro** [alshedivat/al-folio#1534]
I can successfully run the webpages with ```bundle exec jekyll serve``` command. But when I try to deploy in github, the following errors shows in terminal:

```
Deploying...
Source branch: master
Deploy branch: gh-pages
Do you want to proceed? [y/N] y
Already on 'master'
Your branch is up to date with 'origin/master'.
Deleted branch gh-pages (was 49b420c).
Switched to a new branch 'gh-pages'
Configuration file: C:/Users/youjer/Downloads/Code/anmspro.github.io/_config.yml
            Source: C:/Users/youjer/Downloads/Code/anmspro.github.io
       Destination: C:/Users/youjer/Downloads/Code/anmspro.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
"Fetching external posts from medium.com:"
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
       Imagemagick: Disabled in site.config
       Jekyll Feed: Generating feed for posts
   Jekyll Diagrams: Command Not Found: mmdc
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
           Warning: Empty `slug` generated for ''.
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:39:in `exec': SyntaxError: Expected identifier, string or number (ExecJS::RuntimeError)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:14:in `initialize'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/execjs-2.8.1/lib/execjs/runtime.rb:72:in `new'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/execjs-2.8.1/lib/execjs/runtime.rb:72:in `compile'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/execjs-2.8.1/lib/execjs/module.rb:27:in `compile'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/uglifier-4.2.0/lib/uglifier.rb:184:in `context'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/uglifier-4.2.0/lib/uglifier.rb:166:in `compile'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/htmlcompressor-0.4.0/lib/htmlcompressor/compressor.rb:546:in `compress_javascript'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/htmlcompressor-0.4.0/lib/htmlcompressor/compressor.rb:502:in `block in process_script_blocks'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/htmlcompressor-0.4.0/lib/htmlcompressor/compressor.rb:501:in `map!'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/htmlcompressor-0.4.0/lib/htmlcompressor/compressor.rb:501:in `process_script_blocks'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/htmlcompressor-0.4.0/lib/htmlcompressor/compressor.rb:490:in `process_preserved_blocks'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/htmlcompressor-0.4.0/lib/htmlcompressor/compressor.rb:216:in `compress'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:79:in `output_html'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:32:in `output_compressed'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:182:in `write'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:231:in `block in write'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:363:in `block in each_site_file'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:363:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:363:in `each_site_file'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:230:in `write'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:82:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby32-x64/bin/jekyll:25:in `load'
        from C:/Ruby32-x64/bin/jekyll:25:in `<main>'
```

I am running this on windows 10. I have installed ruby and bundler locally. How do I resolve this issue and deploy the website in github?

**Comment by anmspro** [comment]
It seems node.js was not installed in my machine. I installed node.js and restarted the project. After that, it ran smoothly without any errors.
