### ISSUE TITLE
External blogposts from substack appear locally but throws an error upon deployment

### ISSUE THREAD

**Issue by aqcheng** [alshedivat/al-folio#2116]
**Acknowledge the following**

- [X] I carefully read and followed the [Getting Started](../../README.md#getting-started) guide.
- [X] I read through [FAQ](../../FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
I have a website that has been working fine. I recently decided to move my blog to substack and use the external RSS feed instead, but I am getting the error 

```
/home/runner/work/aqcheng.github.io/aqcheng.github.io/vendor/bundle/ruby/3.0.0/gems/feedjira-3.2.2/lib/feedjira.rb:63:in `parse': No valid parser for XML. (Feedjira::NoParserAvailable)
```

and the website fails to deploy. It works again when I remove the external feed from the _config.yml file. The website displays the blogs fine locally. Full error message is attached.
[deploy errmsg.txt](https://github.com/alshedivat/al-folio/files/14017455/deploy.errmsg.txt)

**To Reproduce**

In _config.yml, add an external RSS feed i.e.

```
external_sources:
   - name: substack.com
     rss_url: https://aqcheng.substack.com/feed
```

**Expected behavior**
Github deployment mimics local deployment.

**System (please complete the following information):**

- Jekyll version 4.3.3
- Ruby version 3.1.4 locally, 3.0.2 on Github pages

**Comment by alshedivat** [comment]
I tried adding your external source to config and didn't run into any issues building it locally from the master branch. my only guess is maybe you just need to update ruby to 3.2.2? (both locally and in your github runner config)

**Comment by aqcheng** [comment]
How do I update ruby in my github runner config? Also, I didn't run into any issues building it locally; it's the deployment from github that is problematic

**Comment by alshedivat** [comment]
are you using github actions for automatic deployment? if that's the case, you just need to update the version in `.github/workflows/deploy.yml` config: https://github.com/alshedivat/al-folio/blob/1d84621f220e157d0701d5cbd69f334cb6730a4c/.github/workflows/deploy.yml#L21-L25

**Comment by aqcheng** [comment]
I tried both 3.1.4 (the version I have locally) and 3.2.2, but with no luck. Same error message. I'm positive the problem is with feedjira because it deploys fine when I don't include the external feed, but the ruby, feedjira, and jekyll versions on the Github pages deployment are all identical to my local ruby installation.

I am using `bundle exec jekyll serve` to deploy the website locally (i.e. not using docker), and I believe my website was cloned from v0.6.0. I've customized my website pretty extensively so I think it'd be hard to update it. Do you have any idea what the issue could be?

**Comment by george-gca** [comment]
Before anything try to replicate the GitHub website locally. Do exactly what is done in the [deploy action](https://github.com/alshedivat/al-folio/blob/master/.github/workflows/deploy.yml), more specifically:

```bash
export JEKYLL_ENV=production
bundle exec jekyll build --lsi
```

The `--lsi` is just if you use the related posts part. Then serve the site locally with `python3 -m http.server -d _site/` and test it in `http://localhost:8000/`. When you build the site with `JEKYLL_ENV=production` it does some changes on the build process.

---

One thing that might be causing the issue is older libraries. For instance in #2073 the site of some users were throwing some errors due to deprecated old libraries. Maybe if you update them it could work. Also as I suggested there you could get the tip of master branch and the tip of yours and run a diff between the two directories with a tool like [meld](https://meldmerge.org/) or [winmerge](https://winmerge.org/). They make the process of manual merge a little easier.

**Comment by harmonbhasin** [comment]
Had a similar issue with trying to include my substack. After printing out the variable `xml`, it seems that I'm not even getting the rss feed, but rather am getting the html for a page that says 'Just a moment...', which I assume is CloudFlare blocking Github. 

I found that others had a similar issue, https://github.com/Athou/commafeed/issues/1138. I'm looking into solutions, but I figured I'd leave a comment.

**Comment by harmonbhasin** [comment]
Came up with a solution, it's kind of rough, in external-posts.rb, I added the following line after reading in the xml file,

` if xml.include?('<!DOCTYPE html>')
            xml = File.read('./substack.rss')
end`

where 'substack.rss' is generated by calling the following bash command `curl https://your.substack.com/feed > substack.rss`. This won't update every time you post to substack since it's relying on the file, but it's a good enough temporary fix.

**Comment by george-gca** [comment]
What if you somehow set the user agent used to fetch this information? Like it is done [in here](https://github.com/alshedivat/al-folio/blob/96c4e613854509c37f36ae0e63a616e6be342547/_plugins/download-3rd-party.rb#L95)?

**Comment by lathashree01** [comment]
Hi, I am having similar issue. I am trying to add my external articles from medium.com.
I am getting error like this. How can I fix this

Using docker file to check changes in my local, using latest version: 0.14

My repo is here: https://github.com/lathashree01/lathashree01.github.io

```Fetching external posts from medium.com:
jekyll-1  | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
jekyll-1  | /usr/local/bundle/gems/feedjira-3.2.5/lib/feedjira.rb:59:in 'Feedjira.parse': No valid parser for XML. (Feedjira::NoParserAvailable)
jekyll-1  | 	from /srv/jekyll/_plugins/external-posts.rb:31:in 'ExternalPosts::ExternalPostsGenerator#fetch_from_rss'
jekyll-1  | 	from /srv/jekyll/_plugins/external-posts.rb:17:in 'block in ExternalPosts::ExternalPostsGenerator#generate'
jekyll-1  | 	from /srv/jekyll/_plugins/external-posts.rb:14:in 'Array#each'
jekyll-1  | 	from /srv/jekyll/_plugins/external-posts.rb:14:in 'ExternalPosts::ExternalPostsGenerator#generate'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/site.rb:193:in 'block in Jekyll::Site#generate'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/site.rb:191:in 'Array#each'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/site.rb:191:in 'Jekyll::Site#generate'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/site.rb:79:in 'Jekyll::Site#process'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/command.rb:28:in 'Jekyll::Command.process_site'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/commands/build.rb:65:in 'Jekyll::Commands::Build.build'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/commands/build.rb:36:in 'Jekyll::Commands::Build.process'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/command.rb:91:in 'block in Jekyll::Command.process_with_graceful_fail'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/command.rb:91:in 'Array#each'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/command.rb:91:in 'Jekyll::Command.process_with_graceful_fail'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/lib/jekyll/commands/serve.rb:85:in 'block (2 levels) in Jekyll::Commands::Serve.init_with_program'
jekyll-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in 'block in Mercenary::Command#execute'
jekyll-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in 'Array#each'
jekyll-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in 'Mercenary::Command#execute'
jekyll-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in 'Mercenary::Program#go'
jekyll-1  | 	from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary.rb:21:in 'Mercenary.program'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.4.1/exe/jekyll:15:in '<top (required)>'
jekyll-1  | 	from /usr/local/bundle/bin/jekyll:25:in 'Kernel#load'
jekyll-1  | 	from /usr/local/bundle/bin/jekyll:25:in '<top (required)>'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli/exec.rb:59:in 'Kernel.load'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli/exec.rb:59:in 'Bundler::CLI::Exec#kernel_load'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli/exec.rb:23:in 'Bundler::CLI::Exec#run'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli.rb:452:in 'Bundler::CLI#exec'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in 'Bundler::Thor::Command#run'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in 'Bundler::Thor::Invocation#invoke_command'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor.rb:538:in 'Bundler::Thor.dispatch'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli.rb:35:in 'Bundler::CLI.dispatch'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in 'Bundler::Thor::Base::ClassMethods#start'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/cli.rb:29:in 'Bundler::CLI.start'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/exe/bundle:28:in 'block in <top (required)>'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/lib/bundler/friendly_errors.rb:117:in 'Bundler.with_friendly_errors'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.6.9/exe/bundle:20:in '<top (required)>'
jekyll-1  | 	from /usr/local/bundle/bin/bundle:25:in 'Kernel#load'
jekyll-1  | 	from /usr/local/bundle/bin/bundle:25:in '<main>'
```

**Comment by george-gca** [comment]
Will try to take a look at it @lathashree01.

**Comment by george-gca** [comment]
Actually this is probably related to #3310. Closing this issue in favor of a more recent one.

**Comment by amorehead** [comment]
> Came up with a solution, it's kind of rough, in external-posts.rb, I added the following line after reading in the xml file,
> 
> ` if xml.include?('<!DOCTYPE html>') xml = File.read('./substack.rss') end`
> 
> where 'substack.rss' is generated by calling the following bash command `curl https://your.substack.com/feed > substack.rss`. This won't update every time you post to substack since it's relying on the file, but it's a good enough temporary fix.

@harmonbhasin's solution is the one I went with in a similar circumstance, since it only requires one to manually fetch and commit the latest RSS feed periodically (as a temporary workaround).

For reference, below is what my modified `fetch_from_rss` function within `_plugins/external-posts.rb` looks like:
```ruby
def fetch_from_rss(site, src)
  rss_file = './substack.rss'

  if File.exist?(rss_file)
    xml = File.read(rss_file)
  else
    puts "Error: Failed to find RSS file #{rss_file} of #{src['rss_url']}. Please generate it locally using the command `curl #{src['rss_url']} > #{rss_file}` and try again."
    return
  end

  feed = Feedjira.parse(xml)
  process_entries(site, src, feed.entries)
end
```
