### ISSUE TITLE
Docker Compose Up Fails

### ISSUE THREAD

**Issue by majauhar** [alshedivat/al-folio#2160]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Docker Compose Up fails.

### How to reproduce the bug

1. Go to my website GitHub and clone it: https://github.com/majauhar/majauhar.github.io.git
2. `cd` to the root directory
3. Run `docker compose pull`
4. Run `docker compose up`

### Error messages and logs

```
[+] Running 1/1
 ✔ Container majauhargithubio-jekyll-1  Recreated                                                                               0.3s 
Attaching to al-folio-website
al-folio-website  | bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
al-folio-website  | /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:332:in `raise_not_found!': Could not find gem 'jekyll-diagrams' in locally installed gems. (Bundler::GemNotFound)
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:392:in `block in prepare_dependencies'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:377:in `each'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:377:in `map'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:377:in `prepare_dependencies'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:61:in `setup_solver'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/resolver.rb:28:in `start'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:600:in `start_resolution'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:311:in `resolve'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:553:in `materialize'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:203:in `specs'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/definition.rb:270:in `specs_for'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:18:in `setup'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler.rb:162:in `setup'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/setup.rb:26:in `block in <top (required)>'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/ui/shell.rb:159:in `with_level'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/ui/shell.rb:111:in `silence'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/setup.rb:26:in `<top (required)>'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:56:in `require_relative'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:56:in `kernel_load'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli/exec.rb:23:in `run'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:451:in `exec'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:34:in `dispatch'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/cli.rb:28:in `start'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:28:in `block in <top (required)>'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/exe/bundle:20:in `<top (required)>'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/exe/bundler:4:in `load'
al-folio-website  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.4/exe/bundler:4:in `<top (required)>'
al-folio-website  |     from /usr/local/bin/bundler:25:in `load'
al-folio-website  |     from /usr/local/bin/bundler:25:in `<main>'
al-folio-website exited with code 1
```

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Running locally with Docker

### More info

Just for context, I am using GitHub codespaces. It is a linux environment and it used to work well before the current bug that I have experienced.

**Comment by george-gca** [comment]
`jekyll-diagrams` support was dropped in #1992 in favor of using `mermaid.js` directly. Simply [update your code](https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#upgrading-from-a-previous-version) to get the latest changes.

**Comment by george-gca** [comment]
Updated our FAQ with [information on this matter](https://github.com/alshedivat/al-folio/blob/master/FAQ.md#i-am-trying-to-deploy-my-site-but-it-fails-with-could-not-find-gem-jekyll-diagrams-in-locally-installed-gems-how-do-i-fix-that).

**Comment by john-heyer** [comment]
For those who make it here -- if you're not using `jekyll-diagrams` and don't want to go through the trouble of updating your changes, just remove it from `Gemfile`.

Updating changes was really difficult for me!

**Comment by majauhar** [comment]
@john-heyer Thanks for the pointer. This workaround would work with local setup only, isn't it? Would it work with docker?

**Comment by majauhar** [comment]
Just an update: removing `jekyll-diagrams` really worked, even with docker. Just needed to build docker image on my own. Thanks a lot @john-heyer
