### ISSUE TITLE
Duplicate Blog Post causes Exception

### ISSUE THREAD

**Issue by ywcb00** [alshedivat/al-folio#2290]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

When having two blog posts with the same content but different titles, etc. the index building procedure throws a Liquid Exception.

### How to reproduce the bug

1. Duplicate a blog post
2. Change title and properties but NOT the content
3. Build with `-lsi` flag

### Error messages and logs

```
Liquid Exception: Numerical argument is out of domain - "sqrt" in al-folio-website/_layouts/post.liquid
al-folio-website/vendor/bundle/ruby/3.0.0/gems/classifier-reborn-2.3.0/lib/classifier-reborn/extensions/vector.rb:64:in `sqrt': Numerical argument is out of domain - "sqrt" (Math::DomainError)
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/classifier-reborn-2.3.0/lib/classifier-reborn/extensions/vector.rb:64:in `block in SV_decomp'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/classifier-reborn-2.3.0/lib/classifier-reborn/extensions/vector.rb:63:in `times'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/classifier-reborn-2.3.0/lib/classifier-reborn/extensions/vector.rb:63:in `SV_decomp'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/classifier-reborn-2.3.0/lib/classifier-reborn/lsi.rb:353:in `build_reduced_matrix'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/classifier-reborn-2.3.0/lib/classifier-reborn/lsi.rb:174:in `build_index'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/related_posts.rb:38:in `build_index'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/related_posts.rb:21:in `build'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/document.rb:403:in `related_posts'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/drops/site_drop.rb:58:in `related_posts'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:128:in `public_send'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/drops/drop.rb:128:in `[]'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/drops/site_drop.rb:19:in `[]'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:197:in `lookup_and_evaluate'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/variable_lookup.rb:48:in `block in evaluate'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/variable_lookup.rb:38:in `each_index'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/variable_lookup.rb:38:in `evaluate'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:159:in `evaluate'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/for.rb:130:in `collection_segment'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/for.rb:74:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/inclusion.rb:16:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/tags/include.rb:208:in `block in render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/tags/include.rb:206:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `each'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `block in render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:43:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `each'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:44:in `block in render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/context.rb:123:in `stack'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/tags/if.rb:43:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:82:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:205:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:129:in `render_liquid'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:192:in `render_layout'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:161:in `place_in_layouts'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:93:in `render_document'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/renderer.rb:63:in `run'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:572:in `render_regenerated'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:557:in `block (2 levels) in render_docs'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `each'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:556:in `block in render_docs'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `each_value'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:555:in `render_docs'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:210:in `render'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/site.rb:80:in `process'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:28:in `process_site'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:65:in `build'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:36:in `process'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
 from al-folio-website/vendor/bundle/ruby/3.0.0/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
 from al-folio-website/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `load'
 from al-folio-website/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `<main>'
```

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Running locally without Docker

### More info

I'm not sure if this should be considered a bug since you usually do not create duplicate posts. However, I think it could easily be fixed by someone knowing this code part. Unfortunately, I am new to this repo and I am not familiar to Liquid so I cannot fix it myself.

**Comment by sim642** [comment]
This seems like a classifier-reborn bug.

**Comment by george-gca** [comment]
Usually the error with sqrt is related to related posts. Check the solution related to that in the [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md).
