### ISSUE TITLE
Liquid Syntax Error in _layouts/post.liquid line 59

### ISSUE THREAD

**Issue by david-wei-01001** [alshedivat/al-folio#2319]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Liquid Syntax Error in _layouts/post.liquid line 59 with the original project

### How to reproduce the bug

1. go to https://github.com/alshedivat/al-folio
2. click "Use This Template"
3. In the drop down manu, click "Create a new repository"
4. Now you are in your own repo with this template
5. Do not change anything. Deploy it immediately by doing:
6. Settings -> Pages
7. Set master with /roots and click save
![Screenshot 2024-04-05 at 8 25 29 PM](https://github.com/alshedivat/al-folio/assets/72998341/211a6d13-845a-4386-8b81-45518e3b32f5)
8. Now go to Action, and wait until it fails with "Liquid Syntax Error"

### Error messages and logs

```
Run actions/jekyll-build-pages@v1
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv1012_7e0c17 --label b2dc02 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/temp/temp":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.12
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Warning: The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  Liquid Exception: Liquid syntax error (line 5[9](https://github.com/david-wei-01001/temp/actions/runs/8577271982/job/23509620788#step:4:10)): Unknown tag 'toc' in /_layouts/post.liquid
/usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:38:in `unknown_tag': Liquid syntax error (line 59): Unknown tag 'toc' (Liquid::SyntaxError)
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:38:in `unknown_tag'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:68:in `block in parse_body'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:32:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:58:in `parse_body'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tags/if.rb:30:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/tag.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:34:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:10:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/document.rb:5:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:130:in `parse'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:114:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:121:in `render_liquid'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:195:in `render_layout'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:158:in `place_in_layouts'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:88:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:464:in `block (2 levels) in render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:463:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:463:in `block in render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:462:in `each_value'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:462:in `render_docs'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:191:in `render'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.5/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-231/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-231/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
Error:  Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v231 GitHub Pages: jekyll v3.9.5 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-feed Requiring: jekyll-sitemap Requiring: jemoji Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /docker-compose.yml EntryFilter: excluded /package-lock.json EntryFilter: excluded /Gemfile EntryFilter: excluded /CUSTOMIZE.md EntryFilter: excluded /README.md EntryFilter: excluded /INSTALL.md EntryFilter: excluded /FAQ.md EntryFilter: excluded /LICENSE EntryFilter: excluded /purgecss.config.js EntryFilter: excluded /docker-compose-slim.yml EntryFilter: excluded /package.json EntryFilter: excluded /Dockerfile EntryFilter: excluded /CONTRIBUTING.md Reading: _posts/2023-04-25-audios.md Reading: _posts/2023-04-25-sidebar-table-of-contents.md Reading: _posts/2023-07-12-post-bibliography.md Reading: _posts/2021-07-04-diagrams.md Reading: _posts/2024-01-27-vega-lite.md Reading: _posts/2015-[10](https://github.com/david-wei-01001/temp/actions/runs/8577271982/job/23509620788#step:4:11)-20-math.md Reading: _posts/2015-03-15-formatting-and-links.md Reading: _posts/2024-01-27-code-diff.md Reading: _posts/2015-07-15-code.md Reading: _posts/2023-04-24-videos.md Reading: _posts/2024-01-26-chartjs.md Reading: _posts/2024-01-26-echarts.md Reading: _posts/2020-09-28-github-metadata.md Reading: _posts/2023-[12](https://github.com/david-wei-01001/temp/actions/runs/8577271982/job/23509620788#step:4:13)-12-tikzjax.md Reading: _posts/2023-07-04-jupyter-notebook.md Reading: _posts/2015-10-20-disqus-comments.md Reading: _posts/2024-01-27-advanced-images.md Reading: _posts/2024-01-26-geojson-map.md Reading: _posts/2022-12-10-giscus-comments.md Reading: _posts/2023-03-20-table-of-contents.md Reading: _posts/2015-05-15-images.md Reading: _posts/2018-12-22-distill.md Reading: _posts/2023-03-21-tables.md Reading: _posts/2020-09-28-twitter.md Reading: _posts/2022-02-01-redirect.md Reading: _posts/2023-05-12-custom-blockquotes.md EntryFilter: excluded /bin/cibuild EntryFilter: excluded /bin/deploy EntryFilter: excluded /bin/entry_point.sh EntryFilter: excluded /_pages/about_einstein.md EntryFilter: excluded /lighthouse_results/mobile EntryFilter: excluded /lighthouse_results/desktop EntryFilter: excluded /readme_preview/publications.png EntryFilter: excluded /readme_preview/projects.png EntryFilter: excluded /readme_preview/math.png EntryFilter: excluded /readme_preview/light.png EntryFilter: excluded /readme_preview/blog.png EntryFilter: excluded /readme_preview/al-folio-preview.png EntryFilter: excluded /readme_preview/dark.png EntryFilter: excluded /readme_preview/repositories.png EntryFilter: excluded /readme_preview/people.png EntryFilter: excluded /readme_preview/jupyter.png EntryFilter: excluded /readme_preview/photos-screenshot.png EntryFilter: excluded /readme_preview/cv.png EntryFilter: excluded /readme_preview/distill.png EntryFilter: excluded /readme_preview/code.png Reading: _news/announcement_1.md Reading: _news/announcement_2.md Reading: _news/announcement_3.md Reading: _projects/6_project.md Reading: _projects/3_project.md Reading: _projects/4_project.md Reading: _projects/2_project.md Reading: _projects/1_project.md Reading: _projects/5_project.md Generating: JekyllOptionalFrontMatter::Generator finished in 6.7906e-05 seconds. Generating: JekyllReadmeIndex::Generator finished in 7.5351e-05 seconds. Jekyll Feed: Generating feed for posts Generating: JekyllFeed::Generator finished in 0.000776573 seconds. Generating: Jekyll::JekyllSitemap finished in 0.00[20](https://github.com/david-wei-01001/temp/actions/runs/8577271982/job/23509620788#step:4:21)00048 seconds. Generating: Jekyll::Paginate::Pagination finished in 5.239e-06 seconds. Generating: JekyllRe
```
Pictures also supplied:
![Screenshot 2024-04-05 at 8 29 16 PM](https://github.com/alshedivat/al-folio/assets/72998341/f28e1c2d-83de-43ac-8087-1107aaa52478)

### What operating system are you using?

Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

### More info
This was found when I finish editing my customized webpage and trying to deploy it. The same error appears. I saw that it was in a file that I need not look or change, so I hypothesize that this is an error with the initial repository, so I restart the forking process and deploy immediately to get the default webpage, and yes on this new repo where I did not touch at all, deployment also failed with the same error.

**Comment by george-gca** [comment]
You did it wrong. As stated in the [recommended approach](https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#recommended-approach), you should set to deploy from `gh-pages` branch, NOT `master` branch.

**Comment by david-wei-01001** [comment]
Yeah yeah of course. I resolved the problem by closely following the INSTALL.md.
I was trying to close this issue but I don't know how to. 
Sorry about this!

**Comment by david-wei-01001** [comment]
I propose to change the name INSTALL.md to INSTALL And DEPLOY.md
The reason why I missed it is because I thought I was not installing anything, I am simply deploying it, so I ignored this file...

**Comment by george-gca** [comment]
Will change the name of it in the README, but no need to change the name of the file.
