### ISSUE TITLE
Error during GitHub Actions build

### ISSUE THREAD

**Issue by fareedqk** [alshedivat/al-folio#2346]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

I'm encountering an error during the GitHub Actions build process for my Jekyll site. Despite making changes to my code and configuration, the error persists. 

### How to reproduce the bug

Make changes to the codebase, such as modifying content or configuration files.
Push the changes to the main branch.
Observe the GitHub Actions workflow execution and the error encountered during the build process.errors

### Error messages and logs

```
Bundler can't satisfy your Gemfile's dependencies.
Install missing gems with `bundle install`.
Warning: The github-pages gem can't satisfy your Gemfile's dependencies. If you want to use a different Jekyll version or need additional dependencies, consider building Jekyll site with GitHub Actions: https://jekyllrb.com/docs/continuous-integration/github-actions/
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  Liquid Exception: Liquid syntax error (/github/workspace/_includes/head.liquid line 42): Unknown tag 'localization_exists' included in /_layouts/default.liquid
/usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:38:in `unknown_tag': Liquid syntax error (/github/workspace/_includes/head.liquid line 42): Unknown tag 'localization_exists' included  (Liquid::SyntaxError)
```

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Running locally without Docker

**Comment by george-gca** [comment]
If you make a quick search in our repo for [localization_exists](https://github.com/search?q=repo%3Aalshedivat%2Fal-folio+localization_exists&type=code), you'll see that we don't have this tag here. Are you sure that your repo was created from this template?

**Comment by fareedqk** [comment]
Yes, I am sure. The thing is I am trying to use this template as my portfolio, I tried to fork and then clone it into my local system after that I made some changes pushed my code and did a bundle install to make sure it installs the gem dependencies before deploying and it throws an error.

Actually before 'localization_exists' it was something 'toc' I tried to remove that line in that particular file and the error changed to this.

**Comment by george-gca** [comment]
Just randomly removing the line won't do you any good. My suggestion is, follow our installation instructions to the line. Don't skip the the [Recommended approach](https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#recommended-approach), since this makes sure the repo works for you before anything else. You don't even need a local setup for that part, you can do all that on GitHub itself. So you don't need `bundle install` to make it work on the GitHub pages.

Also try to do small changes at a time, this way it is easier to pinpoint what change breaks the build.

My recommendation is, start over from the beginning, since you still don't have much changes. Like I said, we don't even have the `localization_exists` string in our repository.

**Comment by fareedqk** [comment]
Thank you so much @george-gca. The Recommended approach worked for me!

**Comment by formozov** [comment]
Hi there! 

I am following the Recommended approach but have similar issue. I investigated a bit this issue and it looks like the Warning in the automatic _pages build and deployment_ workflow suggested that the version of the Bundle is not matching.

> Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.5.7). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.5.7`.

I have found that some people suggest to use a custom workflow as a solution, but sounds too complicated:
https://github.com/orgs/community/discussions/67813

Do you know how to resolve this issue and force github use the newer version of the bundler?

**Comment by LukeLIN-web** [comment]
similar 
```
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
  Liquid Exception: Liquid syntax error (line 61): Unknown tag 'toc' in /_layouts/post.liquid
/usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block.rb:38:in `unknown_tag': Liquid syntax error (line 61): Unknown tag 'toc' (Liquid::SyntaxError)
```
