### ISSUE TITLE
docker compose up fails - could not find 'jekyll-tabs'

### ISSUE THREAD

**Issue by albusdemens** [alshedivat/al-folio#2392]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

I cannot run 'docker compose up'

### How to reproduce the bug

1. Clone the repo
2. Install all necessary dependencies using WSL2 - Ubuntu 22.04
3. sudo docker compose pull
4. sudo docker compose up

### Error messages and logs

```
Attaching to jekyll-1
jekyll-1  | /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:332:in `raise_not_found!': Could not find gem 'jekyll-tabs' in locally installed gems. (Bundler::GemNotFound)
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:392:in `block in prepare_dependencies'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:377:in `each'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:377:in `map'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:377:in `prepare_dependencies'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:61:in `setup_solver'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:28:in `start'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:626:in `start_resolution'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:311:in `resolve'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:579:in `materialize'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:203:in `specs'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:270:in `specs_for'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:18:in `setup'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler.rb:162:in `setup'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/jekyll-4.3.3/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
jekyll-1  |     from /var/lib/gems/3.0.0/gems/jekyll-4.3.3/exe/jekyll:11:in `<top (required)>'
jekyll-1  |     from /usr/local/bin/jekyll:25:in `load'
jekyll-1  |     from /usr/local/bin/jekyll:25:in `<main>'```


### What operating system are you using?

Windows

### Where are you seeing the problem on?

Running locally with Docker

### More info

I had the same issues running the command on OSX.

**Comment by george-gca** [comment]
Fixing #2384 also fixes this.
