### ISSUE TITLE
"Could not find gem" when running default `docker-compose.yml` for latest `al-folio` docker image

### ISSUE THREAD

**Issue by doyled-it** [alshedivat/al-folio#2395]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

The jekyll site does not finish initializing and is unreachable at localhost:8080.

### System
MacBook Air
Apple M3
Sonoma 14.4.1

### Steps
1. Clone the repo
2. `docker compose up` (with [this](https://hub.docker.com/layers/amirpourmand/al-folio/latest/images/sha256-c267a4cf8333f40b1e90d63eed9911c225da0b7368da8a207d13a1c4e6c36ad8?context=explore) docker image)

### Behavior

```
[+] Running 2/0
 ✔ Network doyled-itgithubio_default     Created                                                                                                                             0.0s
 ✔ Container doyled-itgithubio-jekyll-1  Created                                                                                                                             0.0s
Attaching to jekyll-1
jekyll-1  | /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:332:in `raise_not_found!': Could not find gem 'jekyll-tabs' in locally installed gems. (Bundler::GemNotFound)
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:392:in `block in prepare_dependencies'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:377:in `each'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:377:in `map'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:377:in `prepare_dependencies'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:61:in `setup_solver'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/resolver.rb:28:in `start'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:626:in `start_resolution'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:311:in `resolve'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:579:in `materialize'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:203:in `specs'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/definition.rb:270:in `specs_for'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:18:in `setup'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/bundler-2.5.7/lib/bundler.rb:162:in `setup'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/jekyll-4.3.3/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
jekyll-1  | 	from /var/lib/gems/3.0.0/gems/jekyll-4.3.3/exe/jekyll:11:in `<top (required)>'
jekyll-1  | 	from /usr/local/bin/jekyll:25:in `load'
jekyll-1  | 	from /usr/local/bin/jekyll:25:in `<main>'
```

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Running locally with Docker

### Fix (for me)

I changed the entry point to include `bundle install` on line 3.

And added this to the `docker-compose.yml` volume:

`- ./bin/entry_point.sh:/tmp/entry_point.sh`

`entry_point.sh`:
```bash
#!/bin/bash

bundle install

CONFIG_FILE=_config.yml

/bin/bash -c "rm -f Gemfile.lock && exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace --force_polling"&

while true; do

  inotifywait -q -e modify,move,create,delete $CONFIG_FILE

  if [ $? -eq 0 ]; then

    echo "Change detected to $CONFIG_FILE, restarting Jekyll"

    jekyll_pid=$(pgrep -f jekyll)
    kill -KILL $jekyll_pid

    /bin/bash -c "rm -f Gemfile.lock && exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload --verbose --trace --force_polling"&

  fi

done
```

This allowed me to run the docker container and reach the dev version of my website.

**Comment by pourmand1376** [comment]
Yep. This is a temporary fix. 

You could also do `docker compose build` and then `docker compose up` to fix it. 

By the way can you paste the content of your`Gemfile.lock` here?

**Comment by george-gca** [comment]
Related to #2384.
