### ISSUE TITLE
Nokogiri mach-o, but wrong architecture

### ISSUE THREAD

**Issue by maellecoursonnais** [alshedivat/al-folio#250]
Dear all,

I've been trying to follow the instructions on the getting started page, but impossible to get around this problem. I had a similar problem than [here](https://github.com/alshedivat/al-folio/issues/240). I'm very new to all of this, but I guess it has to do with the version nokogiri is installed. I've tried [this](https://stackoverflow.com/questions/67079000/how-to-run-rails-console-without-nokogiri-cannot-load-such-file-nokogiri-n/67080501#67080501), but it's not working in my case. Any advice?

I'm using chruby 3.0.1. 

Here's the command: 
```
bundle exec jekyll serve
bundler: failed to load command: jekyll (/Users/maellecoursonnais/.gem/ruby/3.0.1/bin/jekyll)
/Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri/extension.rb:25:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri/extension.rb:25:in `rescue in <top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri/extension.rb:4:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri.rb:11:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri.rb:11:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:66:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:61:in `each'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:61:in `block in require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:50:in `each'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:50:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler.rb:173:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/jekyll-4.2.0/exe/jekyll:11:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/bin/jekyll:23:in `load'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/bin/jekyll:23:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/bin/bundle:23:in `load'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/bin/bundle:23:in `<main>'
/Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri/extension.rb:6:in `require': dlopen(/Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri/3.0/nokogiri.bundle, 9): no suitable image found.  Did find: (LoadError)
	/Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri/3.0/nokogiri.bundle: mach-o, but wrong architecture
	/Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri/3.0/nokogiri.bundle: mach-o, but wrong architecture - /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri/3.0/nokogiri.bundle
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri/extension.rb:6:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri.rb:11:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/nokogiri-1.11.3-arm64-darwin/lib/nokogiri.rb:11:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/html-pipeline-2.14.0/lib/html/pipeline.rb:3:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/jemoji-0.12.0/lib/jemoji.rb:4:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:66:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:61:in `each'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:61:in `block in require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:50:in `each'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/runtime.rb:50:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler.rb:173:in `require'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/jekyll-4.2.0/exe/jekyll:11:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/bin/jekyll:23:in `load'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/bin/jekyll:23:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/bin/bundle:23:in `load'
	from /Users/maellecoursonnais/.gem/ruby/3.0.1/bin/bundle:23:in `<main>'
```

Any help is appreciated!

**Comment by alshedivat** [comment]
Sorry, I'm not able to reproduce the issue since I'm using Apple M1. I hope someone else could chime in and help.

**Comment by DSoko2** [comment]
I faced the same issue using the system's pre-installed ruby 2.6. Running it with ruby 2.7.3 via rbenv solved the issue for me.

**Comment by litinghu** [comment]
I have the same issue when using ruby 2.6.3p62

**Comment by RafalKucharskiPK** [comment]
same here after update to BigSur on mac
