### ISSUE TITLE
Problem with docker compose

### ISSUE THREAD

**Issue by angel-ayala** [alshedivat/al-folio#2795]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

I'm facing problems with the docker setup, when I initialize the container it says: Could not find a JavaScript runtime. I'm not sure if have nodejs on the system but if is a docker container all should be wrapped on it right?

### How to reproduce the bug

1. Download repository and enter to the repo's folder
2. `docker compose pull`
3. `docker compose up`

### Error messages and logs

```
[+] Running 1/0
 ✔ Container al-folio-jekyll-1  Created                                                                                        0.0s 
Attaching to jekyll-1
jekyll-1  | Resolving dependencies...
jekyll-1  | /usr/local/bundle/gems/execjs-2.9.1/lib/execjs/runtimes.rb:68:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
jekyll-1  | 	from /usr/local/bundle/gems/execjs-2.9.1/lib/execjs.rb:5:in `<module:ExecJS>'
jekyll-1  | 	from /usr/local/bundle/gems/execjs-2.9.1/lib/execjs.rb:4:in `<top (required)>'
jekyll-1  | 	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
jekyll-1  | 	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
jekyll-1  | 	from /usr/local/bundle/gems/uglifier-4.2.0/lib/uglifier.rb:5:in `<top (required)>'
jekyll-1  | 	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
jekyll-1  | 	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:1:in `<top (required)>'
jekyll-1  | 	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
jekyll-1  | 	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
jekyll-1  | 	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:55:in `each'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:55:in `block in require'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:44:in `each'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler/runtime.rb:44:in `require'
jekyll-1  | 	from /usr/local/bundle/gems/bundler-2.5.14/lib/bundler.rb:212:in `require'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.3.3/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
jekyll-1  | 	from /usr/local/bundle/gems/jekyll-4.3.3/exe/jekyll:11:in `<top (required)>'
jekyll-1  | 	from /usr/local/bundle/bin/jekyll:25:in `load'
jekyll-1  | 	from /usr/local/bundle/bin/jekyll:25:in `<main>'
```

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Running locally with Docker (docker compose)

### More info

I'm running Manjaro/Arch linux

**Comment by george-gca** [comment]
So THAT's what `mini_racer` was for. I removed it in #2791, will try to find a fix for this.

**Comment by george-gca** [comment]
I might need your help for this @pourmand1376. I tried to change `mini_racer` for `nodejs`, since it is one of the options suggested in the error link https://github.com/rails/execjs (and also we use some tools installed via npm like `prettier`).

I created this `Dockerfile`:

```dockerfile
FROM ruby:latest
ENV DEBIAN_FRONTEND noninteractive

Label MAINTAINER Amir Pourmand

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        imagemagick \
        inotify-tools \
        locales \
        procps \
        python3-pip \
        zlib1g-dev && \
    pip --no-cache-dir install --upgrade --break-system-packages nbconvert

RUN apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*  /tmp/*

ENV NODE_VERSION=23.0.0 \
    NVM_DIR=/root/.nvm \
    NVM_VERSION=0.40.1

# Install node version manager (nvm)
RUN curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh" | bash && \
    . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION} && \
    . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION} && \
    . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}

ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

# check if installation was successful
RUN node --version && npm --version

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    JEKYLL_ENV=production

RUN mkdir /srv/jekyll

ADD Gemfile.lock /srv/jekyll
ADD Gemfile /srv/jekyll

WORKDIR /srv/jekyll

# install jekyll and dependencies
RUN gem install --no-document jekyll bundler
RUN bundle install --no-cache

EXPOSE 8080

COPY bin/entry_point.sh /tmp/entry_point.sh

CMD ["/tmp/entry_point.sh"]

```

Then I run `docker compose build` successfully, but `docker compose up` fails with:

```
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
/usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/cache.rb:181:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/.jekyll-cache/Jekyll/Cache/Jekyll--Cache/b7/9606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910 (Errno::EACCES)
```

Full stack trace

```
Gemfile.lock is tracked by git, keeping it intact
/usr/local/bundle/gems/jekyll-scholar-7.1.3/lib/jekyll/scholar.rb:7: warning: observer was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add observer to your Gemfile or gemspec to silence this warning.
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:75: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
  Logging at level: debug
    Jekyll Version: 4.3.4
Configuration file: /srv/jekyll/_config.yml
  Logging at level: debug
    Jekyll Version: 4.3.4
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
/usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/cache.rb:181:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/.jekyll-cache/Jekyll/Cache/Jekyll--Cache/b7/9606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910 (Errno::EACCES)
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/cache.rb:181:in `open'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/cache.rb:181:in `dump'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/cache.rb:97:in `[]='
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/cache.rb:41:in `clear_if_config_changed'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/site.rb:118:in `reset'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/site.rb:35:in `initialize'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb:30:in `new'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb:30:in `process'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `each'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
    from /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
    from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
    from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
    from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
    from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
    from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
    from /usr/local/bundle/gems/jekyll-4.3.4/exe/jekyll:15:in `<top (required)>'
    from /usr/local/bundle/bin/jekyll:25:in `load'
    from /usr/local/bundle/bin/jekyll:25:in `<top (required)>'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `load'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in `run'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in `exec'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
    from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
    from /usr/local/bundle/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
    from /usr/local/bundle/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
    from /usr/local/bundle/bin/bundle:25:in `load'
    from /usr/local/bundle/bin/bundle:25:in `<main>'
```

Have you struggled with this?

**Comment by NirajPudasaini** [comment]
any updates? same error

**Comment by 0xAdriaTorralba** [comment]
Same error here :(

**Comment by george-gca** [comment]
We are working on this.

**Comment by 0xAdriaTorralba** [comment]
Great. I found that changing the docker image to `v0.12.0` makes it work again. If you don't need the latest features to test locally this does the trick.

**Comment by pourmand1376** [comment]
Unfortunately, I have no idea here. But I can work on it soon.

**Comment by kartikey2001** [comment]
Hi @george-gca @pourmand1376 I've fixed this issue. there were some commands missing in the dockerfile.
<img src="https://github.com/user-attachments/assets/c5d208a3-2f3e-4336-a30d-c36ace3261f5" alt="screenshot" height="300">


Could I send in the PR, for you to check ?

**Comment by angel-ayala** [comment]
@0xAdriaTorralba I also tried changing the version image version with no luck, I don't know if there is some related to the host platform.

@kartikey2001 at first sight seems to be a quick fix to install `nodejs` through `apt-get` but the fix maybe should bee between line 6 - 12 of the `Dockerfile`, how you tested it? did you build your own docker image?

**Comment by pourmand1376** [comment]
> Hi @george-gca @pourmand1376 I've fixed this issue. there were some commands missing in the dockerfile. <img alt="screenshot" height="300" src="https://private-user-images.githubusercontent.com/93374415/379176329-c5d208a3-2f3e-4336-a30d-c36ace3261f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Nzc3NDksIm5iZiI6MTcyOTY3NzQ0OSwicGF0aCI6Ii85MzM3NDQxNS8zNzkxNzYzMjktYzVkMjA4YTMtMmYzZS00MzM2LWEzMGQtYzM2YWNlMzI2MWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA5NTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MmQ1MDYzNzQ4NzI1Y2RlM2M2YjM0ODU0MTFiMWU1ODcyM2E1NGViZjQ5NWMxZDcyMzkwYzJkMjBiNjU5YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q-SaKwuvQMqbuRX64WQyqOXM3HXMu8V80T_PngNHxb8">
> 
> Could I send in the PR, for you to check ?

Definitely. Please Make a PR.

**Comment by 0xAdriaTorralba** [comment]
> @0xAdriaTorralba I also tried changing the version image version with no luck, I don't know if there is some related to the host platform.

😕 I only changed the target on the docker compose and it worked. I have an M1 Max MBP in case it helps. But it seems that it will be fixed soon :)

**Comment by george-gca** [comment]
> 😕 I only changed the target on the docker compose and it worked. I have an M1 Max MBP in case it helps. But it seems that it will be fixed soon :)

What do you mean @0xAdriaTorralba?

@pourmand1376 I tried the new Dockerfile and still get the same error. Idk if it is a linux issue:

```
docker compose pull
docker compose build
docker compose up
```

```
/usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/site.rb:509:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/.jekyll-cache/.gitignore (Errno::EACCES)
```

**Comment by george-gca** [comment]
Just found out how to solve this, and commited this to our repo. Basically I had to create a user inside the Docker image that has the same id and group id as my user in the system, so it has the right permissions to write to the directory.

**Comment by angel-ayala** [comment]
Hi, I got an error saying that there is missing a manifest. Here is the `docker compose pull`'s output

```
[+] Pulling 1/1
 ! jekyll Warning manifest for amirpourmand/al-folio:v0.12.1 not found: manifest unknown: manifest unknown                     1.5s 
WARNING: Some service image(s) must be built from source by running:
    docker compose build jekyll
1 error occurred:
	* Error response from daemon: manifest for amirpourmand/al-folio:v0.12.1 not found: manifest unknown: manifest unknown
```

**Comment by angel-ayala** [comment]
Apparently you miss to pull the tag for `v0.12.1`

**Comment by george-gca** [comment]
@pourmand1376 can we force push the `v0.12.1` tag to docker hub?

**Comment by pourmand1376** [comment]
For now, I've changed it to latest. 

But no. We cannot force push it.

**Comment by george-gca** [comment]
Actually I just realized that WE CAN make a release (at least seems so). Would you make the honors?

**Comment by pourmand1376** [comment]
Thanks. I just released a new version. 

I will also revert the tag on docker-compose to be `v0.12.1`.

**Comment by george-gca** [comment]
I believe this is now fixed in the [latest release](https://github.com/alshedivat/al-folio/releases/tag/v0.12.1).

**Comment by angel-ayala** [comment]
I just did `git pull` , followed of  `docker compose pull` and `docker compose up` and it is working, thanks for the quick fix.
