### ISSUE TITLE
website not building when `url` under `_config.yml` is left blank

### ISSUE THREAD

**Issue by p-costa** [alshedivat/al-folio#422]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
The website deployment in CI is failing, with my website in sync with 533bed5. I wonder if this is a bug on `al-folio`, or something I should change on my end. Here is the log:

```
Run yes | bin/deploy --verbose  --src main --deploy gh-pages
  yes | bin/deploy --verbose  --src main --deploy gh-pages
  shell: /usr/bin/bash -e {0}
+ shift
+ [[ 4 > 0 ]]
+ key=--src
+ case $key in
+ SRC_BRANCH=main
+ shift
+ shift
+ [[ 2 > 0 ]]
+ key=--deploy
+ case $key in
+ DEPLOY_BRANCH=gh-pages
+ shift
+ shift
+ [[ 0 > 0 ]]
+ set -e
+ echo Deploying...
Deploying...
+ echo 'Source branch: main'
Source branch: main
+ echo 'Deploy branch: gh-pages'
Deploy branch: gh-pages
+ read -r -p 'Do you want to proceed? [y/N] ' response
+ [[ ! y =~ ^([yY][eE][sS]|[yY])+$ ]]
+ git diff-index --quiet HEAD --
++ git ls-files --exclude-standard --others
+ test -z ''
++ git branch
++ tr ' ' '\n'
++ grep main
++ tail -1
+ '[' main ']'
+ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
++ git branch
++ grep gh-pages
+ '[' ']'
+ git checkout -b gh-pages
Switched to a new branch 'gh-pages'
+ bundle exec jekyll build
Configuration file: /home/runner/work/p-costa.github.io/p-costa.github.io/_config.yml
            Source: /home/runner/work/p-costa.github.io/p-costa.github.io
       Destination: /home/runner/work/p-costa.github.io/p-costa.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?): nil (URI::InvalidURIError)
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/uri/rfc3986_parser.rb:15:in `split'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:196:in `external?'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:92:in `processable_link?'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:78:in `block in process_anchor_tags'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:77:in `process_anchor_tags'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:65:in `process_html'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:35:in `process'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:335:in `block in <top (required)>'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/hooks.rb:103:in `block in trigger'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/hooks.rb:102:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/hooks.rb:102:in `trigger'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/document.rb:392:in `trigger_hooks'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:548:in `render_regenerated'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:531:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:531:in `block in render_docs'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:530:in `each_value'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:530:in `render_docs'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:210:in `render'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:80:in `process'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:28:in `process_site'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `load'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli.rb:478:in `exec'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli.rb:31:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli.rb:25:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/exe/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/exe/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `<main>'
/opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/uri/rfc3986_parser.rb:16:in `split': undefined method `to_str' for nil:NilClass (NoMethodError)
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/uri/rfc3986_parser.rb:72:in `parse'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/3.0.0/uri/common.rb:171:in `parse'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:196:in `external?'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:92:in `processable_link?'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:78:in `block in process_anchor_tags'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/nokogiri-1.12.5-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:77:in `process_anchor_tags'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:65:in `process_html'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:35:in `process'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:335:in `block in <top (required)>'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/hooks.rb:103:in `block in trigger'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/hooks.rb:102:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/hooks.rb:102:in `trigger'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/document.rb:392:in `trigger_hooks'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:548:in `render_regenerated'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:531:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:531:in `block in render_docs'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:530:in `each_value'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:530:in `render_docs'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:210:in `render'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:80:in `process'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:28:in `process_site'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `load'
	from /home/runner/work/p-costa.github.io/p-costa.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli.rb:478:in `exec'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli.rb:31:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/cli.rb:25:in `start'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/exe/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/lib/ruby/gems/3.0.0/gems/bundler-2.2.29/exe/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/3.0.2/x64/bin/bundle:23:in `<main>'
yes: standard output: Broken pipe
Error: Process completed with exit code 1.
```
I hope this is enough information (the website is in a private repository). Thanks in advance!

**EDIT:** I manage to visualize the website with `bundle exec jekyll serve`, but with `bundle exec jekyll build` I get the same error in my local machine as in the CI.

**Comment by alshedivat** [comment]
@p-costa, thanks for brining this up. correct, after adding target blank plugin in #404, it is now required to specify `url` in `_config.yml`. I did update the deployment section of README to reflect that, but looks like I forgot to change the FAQ section (updated just now). I hope this is not that big of an inconvenience, which also comes with huge added benefit of the target blank plugin that automatically detects external links and correctly sets their properties.

**Comment by adib2149** [comment]
Just wanted to update on this, I spent the last two weeks finding a solution to this bug! I finally solved it a few minutes ago, and then found this issue here. 

Can we have clear README instructions for the previous al-folio users that they need to fill this when updating the code?

**Comment by tirtharajdash** [comment]
I have run into this issue. Now, although I set my url: https://my-page-url-here, while I deploy (using ./bin/deploy --user), it runs into the same issue. And, then when I checked _config.yml, the url: #https:///my-page-url-here (that is, the deploy code is commenting the url out). What am I doing wrong?
