### ISSUE TITLE
Error when "bundle install": eventmachine, sassc

### ISSUE THREAD

**Issue by DoHaiSon** [alshedivat/al-folio#525]
**Describe the bug**
Bulk error in the first time install package of ruby by "bundle install".

**To Reproduce**
1. `git clone https://github.com/alshedivat/al-folio`
2. `cd al-folio`
3. `bundle install`

**System (please complete the following information):**
 - OS: Windows 10
 - Browser: EDGE latest
 - Jekyll version: not installed because this error
 - Ruby version: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x64-mingw-ucrt]

**Additional context**
```
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using concurrent-ruby 1.1.9
Using minitest 5.15.0
Using zeitwerk 2.5.3
Using public_suffix 4.0.6
Using bundler 2.3.5
Using latex-decode 0.3.2
Using namae 1.1.1
Using rexml 3.2.5
Using colorator 1.1.0
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Fetching eventmachine 1.2.7
Fetching http_parser.rb 0.8.0
Using faraday-excon 1.1.0
Using faraday-httpclient 1.0.1
Using multipart-post 2.1.1
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using faraday-rack 1.0.0
Using ruby2_keywords 0.0.5
Using faraday-retry 1.0.3
Using ffi 1.15.5 (x64-mingw-ucrt)
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using racc 1.6.0
Using mini_portile2 2.6.1
Using htmlbeautifier 1.3.1
Using htmlcompressor 0.4.0
Using rb-fsevent 0.11.0
Using liquid 4.0.3
Using mercenary 0.4.0
Using rouge 3.27.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.8.0
Using jekyll-email-protect 1.1.0
Using jekyll-twitter-plugin 2.1.0
Using unicode_utils 1.4.0
Using webrick 1.7.0
Using i18n 1.8.11
Using tzinfo 2.0.4
Using addressable 2.8.0
Using bibtex-ruby 6.0.0
Using citeproc 1.0.10
Using csl 1.6.0
Using kramdown 2.3.1
Using faraday-multipart 1.0.3
Using rb-inotify 0.10.1
Fetching sassc 2.4.0
Using pathutil 0.16.2
Fetching nokogiri 1.12.5
Installing http_parser.rb 0.8.0 with native extensions
Installing eventmachine 1.2.7 with native extensions
Installing sassc 2.4.0 with native extensions
Installing nokogiri 1.12.5 with native extensions
Using terminal-table 2.0.0
Using activesupport 6.1.4.4
Using citeproc-ruby 1.1.14
Using csl-styles 1.0.1.11
Using faraday 1.9.3
Using kramdown-parser-gfm 1.1.0
Using listen 3.7.0
Using sawyer 0.8.2
Using jekyll-watch 2.2.1
Using octokit 4.22.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/eventmachine-1.2.7/ext
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r
./siteconf20220114-6916-vt3599.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby31-x64/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-dir
        --without-openssl-dir
        --with-openssl-include
        --without-openssl-include=${openssl-dir}/include
        --with-openssl-lib
        --without-openssl-lib=${openssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-crypto-dir
        --without-crypto-dir
        --with-crypto-include
        --without-crypto-include=${crypto-dir}/include
        --with-crypto-lib
        --without-crypto-lib=${crypto-dir}/lib
        --with-cryptolib
        --without-cryptolib
C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to
generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:591:in `try_link0'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:609:in `try_link'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:837:in `try_func'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:1065:in `block in have_library'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:1007:in `block in checking_for'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:362:in `block (2 levels) in postpone'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:362:in `block in postpone'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:358:in `postpone'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:1006:in `checking_for'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:1060:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/eventmachine-1.2.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/eventmachine-1.2.7 for inspection.
Results logged to
C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/eventmachine-1.2.7/gem_make.out

  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in
build'
  C:/Ruby31-x64/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
build_extensions'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:847:in `build_extensions'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/source/rubygems.rb:204:in
`install'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:54:in
`install'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:62:in
`apply_func'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:57:in
`block in process_queue'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:54:in
`loop'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:54:in
`process_queue'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing eventmachine (1.2.7), and Bundler cannot
continue.

In Gemfile:
  jekyll-archives was resolved to 2.2.1, which depends on
    jekyll was resolved to 4.2.1, which depends on
      em-websocket was resolved to 0.5.3, which depends on
        eventmachine


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r
./siteconf20220114-6916-8dhviw.rb extconf.rb
creating Makefile

current directory:
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
make DESTDIR\= clean
current directory:
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
make DESTDIR\=
make failedNo such file or directory - make

Gem files will remain installed in
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/http_parser.rb-0.8.0 for inspection.
Results logged to
C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/http_parser.rb-0.8.0/gem_make.out

  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:70:in `rescue in run'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:67:in `run'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:44:in `block in make'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:36:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:36:in `make'
C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:63:in `block in
build'
  C:/Ruby31-x64/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
build_extensions'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:847:in `build_extensions'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/source/rubygems.rb:204:in
`install'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:54:in
`install'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:62:in
`apply_func'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:57:in
`block in process_queue'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:54:in
`loop'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:54:in
`process_queue'
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/bundler-2.3.5/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing http_parser.rb (0.8.0), and Bundler cannot
continue.

In Gemfile:
  jekyll-archives was resolved to 2.2.1, which depends on
    jekyll was resolved to 4.2.1, which depends on
      em-websocket was resolved to 0.5.3, which depends on
        http_parser.rb
```

**Comment by alshedivat** [comment]
@DoHaiSon, thanks for reporting this. this is tricky b/c your OS is Windows, and... I don't have access or used Windows for the last decade or so, and won't be able to help much debugging this.

probably the best solution to get local build working is using docker (see #532) — perhaps you could copy over the dockerfile and follow the steps outlined in that PR? (it'll hopefully be merged into master soon.)

**Comment by DoHaiSon** [comment]
Thx for ur response, year this error is gone after I dongraded to Ruby 2.7 but the complies time stills really slow. So I switch to run Jekyll in the Wsl2, and all work fine.

**Comment by salvatoreloguercio** [comment]
Same error on a macOS Monterey - 12.13.1.

**Comment by jpmorgan98** [comment]
Same error on WSL2 and PopOS/22.04 LTS
