### ISSUE TITLE
libv8 error

### ISSUE THREAD

**Issue by sudarshansudarshan** [alshedivat/al-folio#847]
I have the latest version of mac monterery 12.5.1

I just cloned the repository, installed jekyll. Everything worked fine, but all of a sudden there is this following error:

Installing libv8-node 16.10.0.0 with native extensions
Using feedjira 3.2.1
Using jekyll 4.2.2
Using jekyll-archives 2.2.1
Using jekyll-diagrams 0.10.0
Using jekyll-target-blank 2.0.0
Using jemoji 0.12.0
Using jekyll-feed 0.16.0
Using jekyll-paginate-v2 3.0.0
Using jekyll-imagemagick 1.4.0
Using jekyll-minifier 0.1.10
Using jekyll-scholar 7.1.0
Using jekyll-sitemap 1.4.0
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/ext/libv8-node
/Users/sudarshaniyengar/.rubies/ruby-3.1.2/bin/ruby -I /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0 -r ./siteconf20220826-30551-luqa7z.rb extconf.rb
creating Makefile
==== in /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/ext/libv8-node
==== running /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/libexec/download-node
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 36 61.6M   36 22.7M    0     0  9814k      0  0:00:06  0:00:02  0:00:04 9828k
100 61.6M  100 61.6M    0     0  10.3M      0  0:00:05  0:00:05 --:--:-- 11.1M
/Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/libexec/../src/node-v16.10.0.tar.gz: OK
==== in /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/ext/libv8-node
==== running /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/libexec/extract-node
patching file tools/icu/icutrim.py
patching file tools/genv8constants.py
==== in /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/ext/libv8-node
==== running /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/libexec/build-libv8
parallel job count: 8
configure: --openssl-no-asm --without-npm --shared --with-intl=full-icu
compilers: CC='clang' CXX='clang++' CC_host='' CXX_host=''
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Please use python3.9 or python3.8 or python3.7 or python3.6.
Node.js configure: Found Python 3.10.6...
/Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/ext/libv8-node/builder.rb:14:in `build_libv8!': failed to build libv8 16.10.0 (Libv8::Node::BuilderError)
	from /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0/ext/libv8-node/location.rb:30:in `install!'
	from extconf.rb:9:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/libv8-node-16.10.0.0 for inspection.
Results logged to /Users/sudarshaniyengar/.gem/ruby/3.1.2/extensions/arm64-darwin-21/3.1.0-static/libv8-node-16.10.0.0/gem_make.out

  /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
  /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  /Users/sudarshaniyengar/.rubies/ruby-3.1.2/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/source/rubygems.rb:207:in `install'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/worker.rb:62:in `apply_func'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/worker.rb:54:in `loop'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/worker.rb:54:in `process_queue'
  /Users/sudarshaniyengar/.gem/ruby/3.1.2/gems/bundler-2.3.21/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing libv8-node (16.10.0.0), and Bundler cannot continue.

In Gemfile:
  mini_racer was resolved to 0.6.3, which depends on
    libv8-node

**Comment by sudarshansudarshan** [comment]
Fixed the problem. Just deleted the .gem folder and that stopped the libv8 error. I hope this entire process of using jekyll becomes a bit more user friendly than what it is :)
