### ISSUE TITLE
Website not building in GitLab CI

### ISSUE THREAD

**Issue by r3econ** [alshedivat/al-folio#851]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**

- Build fails on the CI `bundle exec jekyll build -d public`. The only change I did when compared to the freshly checked-out code was updating url and baseurl.

<img width="821" alt="Screenshot 2022-08-28 at 21 35 19" src="https://user-images.githubusercontent.com/505054/187091480-d2c76865-f915-4d0b-98ce-6716ac05e271.png">

<img width="274" alt="Screenshot 2022-08-28 at 21 39 55" src="https://user-images.githubusercontent.com/505054/187091638-bdecf80e-59aa-4b5c-b218-629c241568e6.png">

The website deployment in CI is failing. I wonder if this is a bug on al-folio, or something I should change on my end. Here is the log:

```
[0KRunning with gitlab-runner 15.3.0~beta.42.gdb7789ca (db7789ca)[0;m
[0K  on blue-5.shared.runners-manager.gitlab.com/default -AzERasQ[0;m
section_start:1661714822:prepare_executor
[0K[0K[36;1mPreparing the "docker+machine" executor[0;m[0;m
[0KUsing Docker executor with image ruby:2.3 ...[0;m
[0KPulling docker image ruby:2.3 ...[0;m
[0KUsing docker image sha256:c0d23ebb3ed63af928b7c4a954de87a5d3c1fe98a2dfcb2a44e685a3e65c3c61 for ruby:2.3 with digest ruby@sha256:78cc821d95c48621e577b6b0d44c9d509f0f2a4e089b9fd0ca2ae86f274773a8 ...[0;m
section_end:1661714853:prepare_executor
[0Ksection_start:1661714853:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner--azerasq-project-38356184-concurrent-0 via runner-azerasq-shared-1661714772-8b38a877...
section_end:1661714856:prepare_script
[0Ksection_start:1661714856:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1m$ eval "$CI_PRE_CLONE_SCRIPT"[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Initialized empty Git repository in /builds/r3econ/rs.com/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out 436d2369 as master...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1661714858:get_sources
[0Ksection_start:1661714858:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:c0d23ebb3ed63af928b7c4a954de87a5d3c1fe98a2dfcb2a44e685a3e65c3c61 for ruby:2.3 with digest ruby@sha256:78cc821d95c48621e577b6b0d44c9d509f0f2a4e089b9fd0ca2ae86f274773a8 ...[0;m
[32;1m$ bundle install[0;m
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Fetching concurrent-ruby 1.1.10
Installing concurrent-ruby 1.1.10
Fetching i18n 0.9.5
Installing i18n 0.9.5
Fetching minitest 5.15.0
Installing minitest 5.15.0
Fetching thread_safe 0.3.6
Installing thread_safe 0.3.6
Fetching tzinfo 1.2.10
Installing tzinfo 1.2.10
Fetching activesupport 5.2.8.1
Installing activesupport 5.2.8.1
Fetching public_suffix 4.0.7
Installing public_suffix 4.0.7
Fetching addressable 2.8.1
Installing addressable 2.8.1
Fetching latex-decode 0.4.0
Installing latex-decode 0.4.0
Fetching bibtex-ruby 4.4.7
Installing bibtex-ruby 4.4.7
Using bundler 1.17.3
Fetching namae 1.1.1
Installing namae 1.1.1
Fetching citeproc 1.0.10
Installing citeproc 1.0.10
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching csl 1.6.0
Installing csl 1.6.0
Fetching citeproc-ruby 1.1.14
Installing citeproc-ruby 1.1.14
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching crass 1.0.6
Installing crass 1.0.6
Fetching csl-styles 1.0.1.11
Installing csl-styles 1.0.1.11
Fetching cssminify2 2.0.1
Installing cssminify2 2.0.1
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Fetching http_parser.rb 0.8.0
Installing http_parser.rb 0.8.0 with native extensions
Fetching em-websocket 0.5.3
Installing em-websocket 0.5.3
Fetching execjs 2.8.1
Installing execjs 2.8.1
Fetching mini_portile2 2.4.0
Installing mini_portile2 2.4.0
Fetching nokogiri 1.10.10
Installing nokogiri 1.10.10 with native extensions
Fetching loofah 2.18.0
Installing loofah 2.18.0
Fetching sax-machine 1.3.2
Installing sax-machine 1.3.2
Fetching feedjira 3.1.2
Installing feedjira 3.1.2
Fetching ffi 1.15.5
Installing ffi 1.15.5 with native extensions
Fetching forwardable-extended 2.6.0
Installing forwardable-extended 2.6.0
Fetching gemoji 3.0.1
Installing gemoji 3.0.1
Fetching html-pipeline 2.14.2
Installing html-pipeline 2.14.2
Fetching htmlcompressor 0.4.0
Installing htmlcompressor 0.4.0
Fetching mime-types-data 3.2022.0105
Installing mime-types-data 3.2022.0105
Fetching mime-types 3.4.1
Installing mime-types 3.4.1
Fetching multi_xml 0.6.0
Installing multi_xml 0.6.0
Fetching httparty 0.20.0
Installing httparty 0.20.0
Fetching rb-fsevent 0.11.1
Installing rb-fsevent 0.11.1
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching sass-listen 4.0.0
Installing sass-listen 4.0.0
Fetching sass 3.7.4
Installing sass 3.7.4
Fetching jekyll-sass-converter 1.5.2
Installing jekyll-sass-converter 1.5.2
Fetching listen 3.5.0
Installing listen 3.5.0
Fetching jekyll-watch 2.2.1
Installing jekyll-watch 2.2.1
Fetching kramdown 2.4.0
Installing kramdown 2.4.0
Fetching liquid 4.0.3
Installing liquid 4.0.3
Fetching mercenary 0.3.6
Installing mercenary 0.3.6
Fetching pathutil 0.16.2
Installing pathutil 0.16.2
Fetching rouge 3.30.0
Installing rouge 3.30.0
Fetching safe_yaml 1.0.5
Installing safe_yaml 1.0.5
Fetching jekyll 3.9.2
Installing jekyll 3.9.2
Fetching jekyll-archives 2.2.1
Installing jekyll-archives 2.2.1
Fetching jekyll-diagrams 0.9.2
Installing jekyll-diagrams 0.9.2
Fetching jekyll-email-protect 1.1.0
Installing jekyll-email-protect 1.1.0
Fetching jekyll-feed 0.13.0
Installing jekyll-feed 0.13.0
Fetching jekyll-imagemagick 1.4.0
Installing jekyll-imagemagick 1.4.0
Fetching json 2.6.2
Installing json 2.6.2 with native extensions
Fetching json-minify 0.0.3
Installing json-minify 0.0.3
Fetching uglifier 4.2.0
Installing uglifier 4.2.0
Fetching jekyll-minifier 0.1.10
Installing jekyll-minifier 0.1.10
Fetching jekyll-paginate-v2 3.0.0
Installing jekyll-paginate-v2 3.0.0
Fetching jekyll-scholar 5.16.0
Installing jekyll-scholar 5.16.0
Fetching jekyll-sitemap 1.4.0
Installing jekyll-sitemap 1.4.0
Fetching jekyll-target-blank 2.0.0
Installing jekyll-target-blank 2.0.0
Fetching jekyll-twitter-plugin 2.1.0
Installing jekyll-twitter-plugin 2.1.0
Fetching jemoji 0.11.1
Installing jemoji 0.11.1
Fetching libv8-node 15.14.0.1 (x86_64-linux-musl)
Installing libv8-node 15.14.0.1 (x86_64-linux-musl)
Fetching mini_racer 0.4.0
Installing mini_racer 0.4.0 with native extensions
Fetching unicode_utils 1.4.0
Installing unicode_utils 1.4.0
Fetching webrick 1.7.0
Installing webrick 1.7.0
Bundle complete! 18 Gemfile dependencies, 71 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
Post-install message from html-pipeline:
-------------------------------------------------
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
-------------------------------------------------
Post-install message from httparty:
When you HTTParty, you must party hard!
Post-install message from sass:

Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

[32;1m$ bundle exec jekyll build -d public[0;m
Configuration file: /builds/r3econ/rs.com/_config.yml
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
SyntaxError: /usr/local/bundle/gems/feedjira-3.1.2/lib/feedjira/date_time_utilities/date_time_pattern_parser.rb:15: syntax error, unexpected keyword_rescue, expecting keyword_end
        rescue StandardError => e
              ^
  /usr/local/bundle/gems/feedjira-3.1.2/lib/feedjira.rb:13:in `require'
  /usr/local/bundle/gems/feedjira-3.1.2/lib/feedjira.rb:13:in `<top (required)>'
  /builds/r3econ/rs.com/_plugins/external-posts.rb:1:in `require'
  /builds/r3econ/rs.com/_plugins/external-posts.rb:1:in `<top (required)>'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/external.rb:58:in `require'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/external.rb:55:in `each'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/plugin_manager.rb:87:in `block in require_plugin_files'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/plugin_manager.rb:85:in `each'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/plugin_manager.rb:85:in `require_plugin_files'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:114:in `setup'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/site.rb:32:in `initialize'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
  /usr/local/bundle/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/bundle/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
  /usr/local/bundle/bin/jekyll:23:in `load'
  /usr/local/bundle/bin/jekyll:23:in `<top (required)>'
section_end:1661714959:step_script
[0Ksection_start:1661714959:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1661714960:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m
```

**Expected behavior**

- Building works

**System (please complete the following information):**

```
Running with gitlab-runner 15.3.0~beta.42.gdb7789ca (db7789ca)
  on blue-5.shared.runners-manager.gitlab.com/default -AzERasQ
Preparing the "docker+machine" executor 00:31
Using Docker executor with image ruby:2.3 ...
Pulling docker image ruby:2.3 ...
Using docker image sha256:c0d23ebb3ed63af928b7c4a954de87a5d3c1fe98a2dfcb2a44e685a3e65c3c61 for ruby:2.3 
```
 - OS: docker image sha256:c0d23ebb3ed63af928b7c4a954de87a5d3c1fe98a2dfcb2a44e685a3e65c3c61 for ruby:2.3
 - Jekyll version 3.9.2
- Ruby version 2.3

**Comment by matifali** [comment]
same issue. Build acion fails in github action

**Comment by JacobFV** [comment]
Same

**Comment by ShockThunder** [comment]
I'll try to help.
1. STEP actions will fail if you don't use "main" branch. Because [action-update](https://github.com/skills/action-update-step/blob/main/action.yml) use hardcoded "main" branch
2. Please take a look at your action. If it looks like this 
![image](https://user-images.githubusercontent.com/20852534/190880083-83a97c51-ae64-41e1-9dfd-fa6ffaa192ba.png)
then it's wrong action. It's auto action by github and can't build jekyll properly.
3. If you use "main" branch and custom action, then try manually trigger "deploy".
![image](https://user-images.githubusercontent.com/20852534/190880119-c7cce432-8ea5-43ad-aff6-f62bfb0d7f7e.png)


Hope it will help.
