### ISSUE TITLE
Gem cannot find mini_racer when depolying files on github

### ISSUE THREAD

**Issue by ahMoosavi** [alshedivat/al-folio#960]
Following this [youtube tutorial](https://www.youtube.com/watch?v=g6AJ9qPPoyc), I am trying to deploy the files of my website on github using (on Windows). Once I run `bin/deploy --user`, I face the following error:

```
$ bin/deploy --user
Deploying...
Source branch: source
Deploy branch: master
Do you want to proceed? [y/N] y
Switched to branch 'source'
Deleted branch master (was ddfbef8).
Switched to a new branch 'master'
C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/resolver.rb:235:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'mini_racer' in locally installed gems. (Bundler::GemNotFound)
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/resolver.rb:228:in `map!'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/resolver.rb:228:in `verify_gemfile_dependencies_are_found!'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/resolver.rb:31:in `start'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:279:in `resolve'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:490:in `materialize'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:187:in `specs'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:244:in `specs_for'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:18:in `setup'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler.rb:161:in `setup'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/setup.rb:20:in `block in <top (required)>'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/ui/shell.rb:136:in `with_level'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/ui/shell.rb:88:in `silence'
        from C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/bundler/setup.rb:20:in `<top (required)>'
        from <internal:C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

Then, I try to install `mini_racer` using `gem install mini_racer -v 0.6.2`, but it does not work as well:

```
$ gem install mini_racer -v 0.6.2
ERROR:  Error installing mini_racer:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/libv8-node-16.10.0.0/ext/libv8-node
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0 extconf.rb
creating Makefile
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/libv8-node-16.10.0.0/ext/libv8-node/builder.rb:12:in `build_libv8!': failed to download node 16.10.0 (Libv8::Node::BuilderError)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/libv8-node-16.10.0.0/ext/libv8-node/location.rb:30:in `install!'
        from extconf.rb:9:in `<main>'
==== in C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/libv8-node-16.10.0.0/ext/libv8-node
==== running C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/libv8-node-16.10.0.0/libexec/download-node

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/libv8-node-16.10.0.0 for inspection.
Results logged to C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/libv8-node-16.10.0.0/gem_make.out
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
```

I also tried `gem install libv8-node` and faced a very similar error ("ERROR: Failed to build gem native extension.") Note that I have already installed `ruby_dev`. Please note that I am a beginner (thanks for your patience!).

**Comment by rohandebsarkar** [comment]
See if you can find a solution in the thread #691. Otherwise, leave a comment there.
